"""Regression fixtures — the published figures, pinned (CLAUDE.md §7).

``tests/fixtures/*.json`` holds the numbers as they appear in SPEC.md §6, together with the
tolerance each is published to. **If a change moves one of these, that is either a bug or a
decision that must be recorded in SPEC.md §11.** It is not something to fix by editing the
fixture.

The deterministic figures are pinned tightly, to their published precision, because they are
exactly reproducible from the parameters. The Monte Carlo figures are pinned to 2% relative,
because they were generated by a reference implementation whose RNG stream this one does not
reproduce — agreement there is to Monte Carlo error, and pretending otherwise would pin
noise.
"""

from __future__ import annotations

import json
import pathlib

import pytest

import model
import montecarlo
import params as params_module
import scenarios

FIXTURES = pathlib.Path(__file__).resolve().parent / "fixtures"

DETERMINISTIC = json.loads((FIXTURES / "deterministic.json").read_text(encoding="utf-8"))
MONTE_CARLO = json.loads((FIXTURES / "montecarlo.json").read_text(encoding="utf-8"))

NAMES = tuple(DETERMINISTIC["scenarios"])


@pytest.fixture(scope="module")
def deterministic_results():
    params = params_module.default_params()
    return montecarlo.deterministic_all(params)


@pytest.fixture(scope="module")
def montecarlo_results():
    params = params_module.default_params()
    return montecarlo.run_all(params, iterations=MONTE_CARLO["iterations"],
                              seed=MONTE_CARLO["seed"])


@pytest.mark.parametrize("name", NAMES)
def test_deterministic_figures_are_pinned(name, deterministic_results):
    """SPEC.md §6's deterministic table, every column, to its published precision."""
    pinned = DETERMINISTIC["scenarios"][name]
    tolerance = DETERMINISTIC["_tolerances"]
    result = deterministic_results[name]

    actual = {
        "hours": result["hours"]["total"],
        "human_cost": result["human_cost"],
        "total_tokens": result["total_tokens"],
        "token_cost": result["token_cost"],
        "total_cost": result["total_cost"],
        "token_share_pp": result["token_share"] * 100.0,
        "e_pp": result["e"] * 100.0,
        "n_fallback": result["n_fallback"],
    }
    for column, expected in pinned.items():
        assert actual[column] == pytest.approx(expected, abs=tolerance[column]), (
            f"{name}.{column}: {actual[column]:.4f} against a pinned {expected}. "
            "This is either a bug or a decision for SPEC.md §11.")


def test_savings_are_pinned(deterministic_results):
    """SPEC.md §6: B 26%, C 38%, D 66%, D+ 62% against A."""
    baseline = deterministic_results[scenarios.BASELINE]["total_cost"]
    for name, expected in DETERMINISTIC["savings_pp"].items():
        saving = (1.0 - deterministic_results[name]["total_cost"] / baseline) * 100.0
        assert saving == pytest.approx(
            expected, abs=DETERMINISTIC["savings_tolerance_pp"]), name


def test_superadditivity_is_pinned(deterministic_results):
    """SPEC.md §6: a multiplicative null of 54%, D at 66%, synergy +12 points."""
    pinned = DETERMINISTIC["superadditivity"]
    baseline = deterministic_results[scenarios.BASELINE]["total_cost"]

    def saving(name):
        return 1.0 - deterministic_results[name]["total_cost"] / baseline

    null = 1.0 - (1.0 - saving("execute_decide")) * (1.0 - saving("execute_deliver"))
    realised = saving("all_three")

    assert null * 100.0 == pytest.approx(pinned["null_pp"], abs=pinned["tolerance_pp"])
    assert realised * 100.0 == pytest.approx(pinned["realised_pp"],
                                             abs=pinned["tolerance_pp"])
    assert (realised - null) * 100.0 == pytest.approx(pinned["synergy_pp"],
                                                     abs=pinned["tolerance_pp"])


@pytest.mark.parametrize("name", NAMES)
def test_monte_carlo_percentiles_are_pinned(name, montecarlo_results):
    """SPEC.md §6's Monte Carlo table at 40,000 iterations, seed 7."""
    pinned = MONTE_CARLO["scenarios"][name]
    tolerance = MONTE_CARLO["tolerance"]
    total = montecarlo_results[name]["percentiles"]["total"]

    for label in ("p50", "p80", "p95"):
        assert total[label] == pytest.approx(pinned[label], rel=tolerance), (
            f"{name}.{label}: {total[label]:,.0f} against a pinned {pinned[label]:,}")
    assert montecarlo_results[name]["ratio_p95_p50"] == pytest.approx(
        pinned["ratio"], abs=0.05)


def test_the_headline_comparison_holds(montecarlo_results):
    """SPEC.md §6: D's P95 sits below A's P50.

    The recommendation's bad case beats the alternative's median — a stronger claim than
    comparing against a point estimate, and the one the whole exercise turns on.
    """
    a = montecarlo_results["execute_only"]["percentiles"]["total"]
    d = montecarlo_results["all_three"]["percentiles"]["total"]
    assert d["p95"] < a["p50"]


def test_quality_investment_buys_tail_reduction_not_expected_value(montecarlo_results):
    """SPEC.md §6: D+ costs more at the P50 and less at the P95.

    Invisible while the escape scaling was uncentred, and the correct way to present D+ to
    a risk-averse decision-maker.
    """
    d = montecarlo_results["all_three"]["percentiles"]["total"]
    q = montecarlo_results["all_three_quality"]["percentiles"]["total"]
    assert q["p50"] > d["p50"], "D+ should cost more at the median"
    assert q["p95"] < d["p95"], "D+ should cost less at the P95"
    assert montecarlo_results["all_three_quality"]["ratio_p95_p50"] == min(
        result["ratio_p95_p50"] for result in montecarlo_results.values())


def test_parameter_uncertainty_adds_little_to_the_tail():
    """SPEC.md §6: with --uncertainty aleatory, D's P95 moves under 2%.

    Correlated escape dominates so completely that our ignorance of the parameters barely
    registers — a result worth reporting rather than assuming.
    """
    pinned = MONTE_CARLO["aleatory_all_three"]
    params = params_module.default_params()
    result = montecarlo.run_scenario("all_three", params,
                                     iterations=MONTE_CARLO["iterations"],
                                     seed=MONTE_CARLO["seed"], uncertainty="aleatory")
    total = result["percentiles"]["total"]
    assert total["p50"] == pytest.approx(pinned["p50"], rel=pinned["tolerance"])
    assert total["p95"] == pytest.approx(pinned["p95"], rel=pinned["tolerance"])


def test_escape_dominates_the_variance_decomposition():
    """SPEC.md §5: freezing escape removes about 72% of the P50->P95 spread.

    Run at 150,000 iterations rather than 40,000: the freeze-one-at-a-time estimator is
    noisy, and at 40,000 the smaller sources scatter by a couple of points either side of
    zero. The dominant share is stable long before that.
    """
    params = params_module.default_params()
    result = montecarlo.run_scenario("all_three", params, iterations=150_000, seed=7,
                                     decompose=True)
    share = result["variance"]["escape"]
    assert share == pytest.approx(MONTE_CARLO["variance_escape_share"],
                                 abs=MONTE_CARLO["variance_escape_tolerance"])
    for source, value in result["variance"].items():
        if source != "escape":
            assert value < 0.05, f"{source} at {value:.3f} is not individually small"


def test_apparatus_reconciles_for_the_quality_scenario():
    """REVIEW.md S1-3: D+ must reconcile from its own parameters, not from a delta table.

    Generation 2,557M + apparatus 7,878M = 10,435M, against the pinned 10.44B. An earlier
    version declared 4,200M of apparatus and would have produced 6.9B, failing its own
    fixture.
    """
    params = params_module.default_params()
    scenario = scenarios.resolve_scenario("all_three_quality", params)
    result = model.deterministic_run(params, scenario)

    assert result["generation_tokens"] == pytest.approx(2557e6, rel=0.005)
    assert result["apparatus_tokens"] == pytest.approx(7878e6, rel=0.001)
    assert result["total_tokens"] == pytest.approx(10.44e9, abs=0.01e9)


@pytest.fixture(scope="module")
def decomposed():
    """One decomposition per scenario, shared by the tests below.

    Eight simulation runs per scenario, so it is worth doing once rather than per test.
    """
    params = params_module.default_params()
    return {name: montecarlo.run_scenario(name, params, iterations=40_000, seed=7,
                                          decompose=True)
            for name in NAMES}


def test_the_decomposition_is_scenario_dependent(decomposed):
    """SPEC.md §5: escape dominates everywhere, but the second driver is not the same.

    The finding this pins is that quoting scenario D alone misleads. In C and D+ escape
    falls to 43-46% and criteria authoring resolves as a clear second driver at about 9%,
    because C carries the unaided S_manual = 3.0 and D+ has the lowest escape rate in the
    set. Documented in SPEC.md §5 and in the README.

    Run at 40,000 rather than the 150,000 the table was measured at, to keep the suite
    quick; the two resolved sources are already stable there, and the bounds are widened to
    cover the larger estimator error.
    """
    pinned = MONTE_CARLO["variance_by_scenario"]
    for name, expected in pinned["escape"].items():
        result = decomposed[name]
        share = result["variance"]["escape"]
        assert share == pytest.approx(expected, abs=pinned["escape_tolerance"]), (
            f"{name}: escape share {share:.3f} against a pinned {expected}")

        criteria = result["variance"]["S"]
        error = result["variance_error"]["S"]
        resolved = abs(criteria) > 2.0 * error
        should_resolve = name in pinned["criteria_hours_resolve_in"]
        assert resolved == should_resolve, (
            f"{name}: criteria hours {'did not resolve' if should_resolve else 'resolved'} "
            f"unexpectedly, at {criteria:.3f} +/- {error:.3f}")
        if should_resolve:
            assert criteria == pytest.approx(pinned["criteria_hours_share"],
                                             abs=pinned["criteria_hours_tolerance"]), name


def test_escape_dominates_every_scenario_even_where_it_is_weakest(decomposed):
    """SPEC.md §5: nothing else comes close to escape, in any scenario."""
    for name in NAMES:
        shares = decomposed[name]["variance"]
        runner_up = max(v for source, v in shares.items() if source != "escape")
        assert shares["escape"] > 3.0 * runner_up, name
